name: chess_game
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bitsdojo_window: ^0.1.6
  chess: ^0.8.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.1.0
  get: ^4.7.2
  package_rename: ^1.10.0
  window_manager: ^0.5.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: ChessMerida
      fonts:
        - asset: assets/fonts/chess_merida_unicode.ttf
